on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install dependencies (Windows)
      run: |
        choco install -y llvm ninja cmake

    - name: Build on Windows (release)
      run: |
        mkdir ${{github.workspace}}\build
        cd ${{github.workspace}}\build
        cmake .. `
          -DCMAKE_C_COMPILER=clang-cl `
          -DCMAKE_CXX_COMPILER=clang-cl `
          -DCMAKE_BUILD_TYPE=Release `
          -DBUILD_TEST=ON `
          -G Ninja
        cmake --build . --config Release